from typing import Protocol, Any, Dict

class LoggerProtocol(Protocol):
    """The contract that all other projects will use."""
    def info(self, msg: str, extra: Dict[str, Any] | None = None) -> None: ...
    def error(self, msg: str, extra: Dict[str, Any] | None = None) -> None: ...
    def warning(self, msg: str, extra: Dict[str, Any] | None = None) -> None: ...
    def debug(self, msg: str, extra: Dict[str, Any] | None = None) -> None: ...