from typing import Protocol, Any

class LoggerProtocol(Protocol):
    """
    Structural interface for logging. 
    Allows swapping loguru for standard logging or other modules.
    """
    def info(self, msg: str, **kwargs: Any) -> None: ...
    def error(self, msg: str, **kwargs: Any) -> None: ...
    def warning(self, msg: str, **kwargs: Any) -> None: ...
    def debug(self, msg: str, **kwargs: Any) -> None: ...

class SecretHandlerProtocol(Protocol):
    def fetch_secret(self, secret_id: str, version_id: str = "latest") -> str: ...